name: Release
on:
  push:
    branches: [main]          

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write        
      issues:   read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }  

      - uses: actions/setup-node@v4
        with: { node-version: 22 }

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 